### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by zhengjian526** [zhengjian526/AI-OTOP#1]
**Needs to do and problems to solve:**

- [ ] Tools : bin result compare script
- [ ] Tools : gen random data type traits
- [ ] Crop fp32
- [ ] Summarize the openmp usage guide
- [x] OpenMP determines the optimal number of threads
